In [1]:
import numpy as np

X = np.random.random((1, 100))  # Univariate series length 100
print(X.shape)
X = np.random.random((3, 200))  # three channel multivariate series length 200
print(X.shape)
X = np.random.random((10, 1, 50))  # Collection of 10 univariate series of length 50
print(X.shape)
X = np.random.random((5, 26, 100))  # Collection of 5 multivariate time series with 26
# channels, length 100
print(X.shape)

(1, 100)
(3, 200)
(10, 1, 50)
(5, 26, 100)


In [2]:
import numpy as np

from aeon.classification import DummyClassifier
from aeon.regression import DummyRegressor

X = np.random.random((5, 1, 10))  # Collection of five series
y1 = np.array(["run", "walk", "run", "run", "walk"])
y2 = np.array([1, 0, 1, 1, 0])
y3 = np.array([0.5, 1.11, 0.545, -0.3675, 2.662])
cls = DummyClassifier()
reg = DummyRegressor()
cls.fit(X, y1)
print(cls.predict(X))
cls.fit(X, y2)
print(cls.predict(X))
reg.fit(X, y2)
print(reg.predict(X))
reg.fit(X, y3)
print(reg.predict(X))

['run' 'run' 'run' 'run' 'run']
[1 1 1 1 1]
[0.6 0.6 0.6 0.6 0.6]
[0.8899 0.8899 0.8899 0.8899 0.8899]


In [1]:
print("hello world")

hello world


In [33]:
import warnings

warnings.filterwarnings("ignore")

In [34]:
from sklearn.linear_model import RidgeClassifierCV
from sklearn.pipeline import make_pipeline

from sktime.datasets import load_UCR_UEA_dataset
from sktime.transformations.panel import channel_selection
from sktime.transformations.panel.rocket import Rocket

In [35]:
# cs = channel_selection.ElbowClassSum()  # ECS
cs = channel_selection.ElbowClassPairwise()  # ECP

In [36]:
rocket_pipeline = make_pipeline(cs, Rocket(), RidgeClassifierCV())

In [40]:
data = "BasicMotions"
X_train, y_train = load_UCR_UEA_dataset(data, split="train", return_X_y=True)
X_test, y_test = load_UCR_UEA_dataset(data, split="test", return_X_y=True)

In [41]:
rocket_pipeline.fit(X_train, y_train)

AssertionError: <code object _fit at 0x139946ef0, file "/Users/cyuab/miniconda3/envs/tscc/lib/python3.12/site-packages/sktime/transformations/panel/rocket/_rocket.py", line 93> != <code object _generate_kernels at 0x12bb4bc00, file "/Users/cyuab/miniconda3/envs/tscc/lib/python3.12/site-packages/sktime/transformations/panel/rocket/_rocket_numba.py", line 14>

In [42]:
from sktime.transformations.panel.channel_selection import ElbowClassPairwise
from sktime.utils._testing.panel import make_classification_problem
X, y = make_classification_problem(n_columns=3, n_classes=3, random_state=42)
cs = ElbowClassPairwise()
cs.fit(X, y)
Xt = cs.transform(X)

In [44]:
cs.distance_frame_

Centroid_badminton_running  Centroid_badminton_standing  \
0                   39.594365                    55.752162   
1                   57.681242                    24.390185   
2                   20.175723                    24.126704   
3                   12.546064                    12.438991   
4                   10.101068                     8.865721   
5                   23.463985                    14.568464   

   Centroid_badminton_walking  Centroid_running_standing  \
0                   48.440187                  63.609638   
1                   27.769918                  60.457571   
2                   22.331360                  25.671667   
3                   12.741693                   6.317531   
4                    9.221755                   6.520057   
5                   13.953242                  18.878171   

   Centroid_running_walking  Centroid_standing_walking  
0                 57.246801                  10.716982  
1                 62.338595                  16.370151  
2                 22.991254                   4.897423  
3                  6.695617                   3.585219  
4                  6.715585                   1.299970  
5                 19.768278                   7.228231

In [46]:
cs.train_time_

18

In [5]:
import dill
dill.dump_session('notebook_env.db')

/Users/cyuab/miniconda3/envs/testing/lib/python3.11/site-packages/dill/_dill.py:422: PicklingWarning: Cannot locate reference to <class '__main__.__DW_OUTPUT_FORMATTER__.<locals>.DataWranglerFormatter'>.
  StockPickler.save(self, obj, save_persistent_id)
/Users/cyuab/miniconda3/envs/testing/lib/python3.11/site-packages/dill/_dill.py:422: PicklingWarning: Cannot pickle <class '__main__.__DW_OUTPUT_FORMATTER__.<locals>.DataWranglerFormatter'>: __main__.__DW_OUTPUT_FORMATTER__.<locals>.DataWranglerFormatter has recursive self-references that trigger a RecursionError.
  StockPickler.save(self, obj, save_persistent_id)


PicklingError: Can't pickle <class '__main__.__DW_OUTPUT_FORMATTER__.<locals>.DataWranglerFormatter'>: it's not found as __main__.__DW_OUTPUT_FORMATTER__.<locals>.DataWranglerFormatter

In [6]:
import numpy as np
from sklearn.metrics import precision_score
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]


In [9]:
precision_score(y_true, y_pred, average='macro')

/Users/cyuab/miniconda3/envs/tscc/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


0.1111111111111111

In [10]:
precision_score(y_true, y_pred, average='micro')


0.3333333333333333

In [11]:
precision_score(y_true, y_pred, average='weighted')


/Users/cyuab/miniconda3/envs/tscc/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


0.1111111111111111

In [12]:
precision_score(y_true, y_pred, average=None)


/Users/cyuab/miniconda3/envs/tscc/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


array([0.33333333, 0.        , 0.        ])

In [14]:
y_pred = [0, 0, 0, 0, 0, 0]


In [15]:
precision_score(y_true, y_pred, average=None)


/Users/cyuab/miniconda3/envs/tscc/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


array([0.33333333, 0.        , 0.        ])

In [16]:
precision_score(y_true, y_pred, average=None, zero_division=1)


array([0.33333333, 1.        , 1.        ])

In [17]:
precision_score(y_true, y_pred, average=None, zero_division=np.nan)

array([0.33333333,        nan,        nan])

In [1]:
print("hello world testing")

hello world testing


In [1]:
print("hello world testing")

hello world testing


In [ ]:
print("hello world testing")

# 9 Archive
It archives some useful code segments I have used in doing this project.

## Test the indexing of array in Python

In [1]:
test = [1,2,3,4]

In [ ]:
test, len(test)

In [ ]:
test[0:4]

In [ ]:
test[3] # test[3] is the last entry of test rather than test[4].

## Save and read from CSV

In [ ]:
import pandas as pd
df = pd.read_csv("../data/temp.csv",
                     low_memory=False)
df.to_csv("../data/temp.csv",
              index=False)
df

## Cast String to Float

In [ ]:
# https://stackoverflow.com/questions/64584736/typecast-a-column-in-pandas-dataframe
# https://stackoverflow.com/questions/8420143/valueerror-could-not-convert-string-to-float-id
# https://stackoverflow.com/questions/1614236/how-do-i-convert-all-of-the-items-in-a-list-to-floats
# https://stackoverflow.com/questions/52112553/convert-a-list-of-floats-to-multiple-columns-of-floats-in-pandas/52113073
# https://stackoverflow.com/questions/3877209/how-to-convert-an-array-of-strings-to-an-array-of-floats-in-numpy

In [11]:
# https://www.digitalocean.com/community/tutorials/python-convert-string-to-float
input_1 = '10.5674'
print(len(input_1))

input_1 = float(input_1)

print(type(input_1))
print('Float Value =', input_1)


7
<class 'float'>
Float Value = 10.5674


## Save string in csv

In [ ]:
# https://stackoverflow.com/questions/12877189/float64-with-pandas-to-csv
# https://stackoverflow.com/questions/12877189/float64-with-pandas-to-csv
# https://stackoverflow.com/questions/21433484/write-float-list-to-csv-file
# https://stackoverflow.com/questions/50817163/pd-to-csv-set-float-format-with-list

In [5]:
# https://stackoverflow.com/questions/51476690/how-to-use-pandas-to-csv-float-format
from io import StringIO
import pandas as pd

mystr = StringIO("""0.02506602 0.05754493 0.36854688
0.02461631 0.0599653 0.43078098
0.02502534 0.06209149 0.44955311
0.4267356675182389 0.1718682822340447 0.5391386354945895
0.426701667727433 0.17191008887193007 0.5391897818631616
0.4266676661681287 0.17195189807522643 0.5392409104354972""")

df = pd.read_csv(mystr, delim_whitespace=True, header=None)

print(df.dtypes)

# 0    float64
# 1    float64
# 2    float64
# dtype: object

file_loc = r'test.dat'
# sep=‘\s+‘什么意思？这是代表什么分隔符号？
# https://blog.csdn.net/weixin_37706204/article/details/120827447
df.to_csv(file_loc, sep=' ', index=False, header=False, float_format="%.8f")

df = pd.read_csv(file_loc, delim_whitespace=True, header=None)

print(df[0].iloc[-1])

# 0.42666767

0    float64
1    float64
2    float64
dtype: object
0.42666767


/var/folders/2w/d1h5t_nn2slf5r75qqdvlt0m0000gn/T/ipykernel_18332/2427653110.py:11: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(mystr, delim_whitespace=True, header=None)
/var/folders/2w/d1h5t_nn2slf5r75qqdvlt0m0000gn/T/ipykernel_18332/2427653110.py:23: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_loc, delim_whitespace=True, header=None)


In [13]:
df

0         1         2
0  0.025066  0.057545  0.368547
1  0.024616  0.059965  0.430781
2  0.025025  0.062091  0.449553
3  0.426736  0.171868  0.539139
4  0.426702  0.171910  0.539190
5  0.426668  0.171952  0.539241

## Save variables

In [6]:
# https://stackoverflow.com/questions/34342155/how-to-pickle-or-store-jupyter-ipython-notebook-session-for-later
import dill
dill.dump_session('notebook_env.db')

In [1]:
import dill
dill.load_session('notebook_env.db')

In [ ]:
# https://stackoverflow.com/questions/59463737/panda-dataframe-persisting-a-list-of-numbers-and-then-reading-it

In [3]:
df3 = pd.DataFrame({'tom': [10,-5,3], 'dave': [15,-1,4], 'al': [14,-1,-1]})
df3


df3.to_csv('my.csv', index=False)

In [6]:
df3

tom  dave  al
0   10    15  14
1   -5    -1  -1
2    3     4  -1

In [7]:
len(df3.loc[0])

3

In [8]:
df3in = pd.read_csv('my.csv')

In [9]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tom     3 non-null      int64
 1   dave    3 non-null      int64
 2   al      3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes
